### ISSUE TITLE
zScale / translateZ?

### ISSUE THREAD

**Issue by heaversm** [roymacdonald/kinectToTexturedOBJ#4]
Hi - I'm trying to export only a certain z depth to OBJ and I noticed that you have some code in your file that controls zScale and translateZ, but that doesn't seem to have any visual effect within the editor - is this feature set up? 

I noticed that within depthToObjExporter.h I can replace 

```
//obj << "v " << r.x << " " << -r.y << " " << -r.z << endl;
```

with

```
if (r.z > 400 && r.z < 1100){ //MH - capture only certain z depth
  obj << "v " << r.x << " " << -r.y << " " << -r.z << endl; 
}
```

but I'd like to be able to set it visually / dynamically.

**Comment by roymacdonald** [comment]
the transZ is implemented and working. It works with up arrow key and down arrow key. The scaleZ is implemented as well butI disabled it because I no longer needed it because using the calibrated data fixed the z scale.
https://github.com/roymacdonald/kinectToTexturedOBJ/blob/master/src/testApp.cpp#L76
if you uncomment it should also work, but note that it is just for vizualization.

**Comment by heaversm** [comment]
Thanks - can you clarify what transZ's function is? It doesn't seem to have any effect within the visual editor itself.

**Comment by roymacdonald** [comment]
it moves the center of the point cloud.
you'll notice the difference while rotating.
